### ISSUE TITLE
example for webassembly

### ISSUE THREAD

**Issue by BenDerPan** [inkyblackness/imgui-go-examples#2]
Hi, dose imgui-go support webassembly ? I hope it can work in web browser.

**Comment by dertseha** [comment]
Hello @BenDerPan !
From a gut feeling I'd have guessed no, though, a quick search revealed [this](https://github.com/greggman/doodles/tree/master/glfw-imgui) - ([live demo here](https://greggman.github.io/doodles/glfw-imgui/out/glfw-imgui.html)), that is based on the original code.

So, since the wrapper is just that, I'd guess there would be a way.

I'll make some attempts, though it will take a few days/weeks until I may find some time. If you are experienced, you may of course also give it a try :)

**Comment by BenDerPan** [comment]
👍 @dertseha , I hope I can help it, but I'm not familiar with it, I will have a try :)

**Comment by dertseha** [comment]
I've made some searches to learn more about wasm targets - and for now it seems it's either not possible, or, if at all, quite complicated.
The best answer was given here: https://stackoverflow.com/a/54946750 

There is at least one project out there that manages to combine Go with existing C code into wasm: https://github.com/therecipe/qt - though I didn't spend time to look into how they do it.

I'd like to close this issue and mark it as "not there yet" :)
